services:
  django:
    container_name: "hello_world"
    build: ./hello_world
    ports:
      - "8000:8000"
    env_file: ./hello_world/.env
    networks:
      - proj_network
#   depends_on:
#      - postgres

# nginx:
#   container_name: "kelassor-nginx"
#   image: nginx:latest
#   ports:
#     - "8083:80"
#   volumes:
#     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#   networks:
#     - kelasor_network
#    depends_on:
#     - django
#      - django_front

# postgres:
#   container_name: "hello_posgres"
#   image: postgres:latest 
#   environment:
#     POSTGRES_DB: postgres
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: mysecretpassword
#   ports: 
#     - "5433:5432"
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   networks:
#     - proj_network

networks:
  proj_network:

#volumes:
#  postgres_data:
